spring:
  datasource:
      url: ${PSQL_URL}
      username: ${PSQL_USERNAME}
      password: ${PSQL_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085